name: Assign PR Author
on: [pull_request]

jobs:
  assign-pr-author:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: samspills/assign-pr-to-author@v1.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
