name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/${{ github.repository_owner }}/ubuntu-ci:jammy-0.1.0
      credentials:
        username: ${{ secrets.ROBOT_GITHUB_USER }}
        password: ${{ secrets.ROBOT_GITHUB_READ_PACKAGES_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_GITHUB_WRITE_PACKAGES_TOKEN }}
        run: |
          task ci-login-ghcr

      - name: Configure builder
        run: |
          task images:configure-builder

      - name: Build and upload images
        env:
          IMAGE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          task images:release
